const query = (selector) => document.querySelector(selector);

export const dom = {
    inputBox: query('.input-box'),
    inputWrapper: query('.input-box-wrapper'),
    attachmentInput: query('#attachmentInput'),
    attachmentTray: query('#attachmentTray'),
    attachmentError: query('#attachmentError'),
    chatArea: query('.chat-area'),
    chatView: query('#chatView'),
    grammarView: query('#grammarView'),
    agentsView: query('#agentsView'),
    agentsSearch: query('#agentsSearch'),
    workspaceView: query('#workspaceView'),
    workspaceGridState: query('#workspaceGridState'),
    workspaceGrid: query('#workspaceGrid'),
    workspaceSession: query('#workspaceSession'),
    workspaceBackBtn: query('#workspaceBackBtn'),
    workspaceSessionIcon: query('#workspaceSessionIcon'),
    workspaceSessionLabel: query('#workspaceSessionLabel'),
    workspaceSplit: query('#workspaceSplit'),
    workspaceDropzone: query('#workspaceDropzone'),
    workspaceFileInput: query('#workspaceFileInput'),
    workspaceBrowseBtn: query('#workspaceBrowseBtn'),
    workspaceFilePreview: query('#workspaceFilePreview'),
    workspaceFileIcon: query('#workspaceFileIcon'),
    workspaceFileName: query('#workspaceFileName'),
    workspaceFileSize: query('#workspaceFileSize'),
    workspaceRemoveFileBtn: query('#workspaceRemoveFileBtn'),
    workspaceFilePreviewBody: query('#workspaceFilePreviewBody'),
    workspaceChatArea: query('#workspaceChatArea'),
    workspaceChatInput: query('#workspaceChatInput'),
    workspaceSendBtn: query('#workspaceSendBtn'),
    createAgentBtn: query('#createAgentBtn'),
    agentsGrid: query('#agentsGrid'),
    agentModal: query('#agentModal'),
    closeAgentModalBtn: query('#closeAgentModalBtn'),
    agentModalForm: query('#agentModalForm'),
    cancelAgentBtn: query('#cancelAgentBtn'),
    customAgentName: query('#customAgentName'),
    customAgentDesc: query('#customAgentDesc'),
    customAgentPrompt: query('#customAgentPrompt'),
    customAgentIconSelector: query('#customAgentIconSelector'),
    activeAgentBadge: query('#activeAgentBadge'),
    clearActiveAgentBtn: query('#clearActiveAgentBtn'),
    grammarInput: query('#grammarInput'),
    grammarCounter: query('#grammarCounter'),
    grammarFixBtn: query('#grammarFixBtn'),
    grammarError: query('#grammarError'),
    grammarResult: query('#grammarResult'),
    grammarDiffPanel: query('#grammarDiffPanel'),
    grammarCleanPanel: query('#grammarCleanPanel'),
    grammarChangesCount: query('#grammarChangesCount'),
    grammarCopyBtn: query('#grammarCopyBtn'),
    grammarTabs: Array.from(document.querySelectorAll('.grammar-tab')),
    emptyStateTemplate: query('#emptyStateTemplate'),
    emptyStateHTML: query('#emptyStateTemplate')?.innerHTML.trim() || '',
    overlay: query('#overlay'),
    modelSelectBtn: query('#modelSelectBtn'),
    modelDropdown: query('#modelDropdown'),
    selectedModelText: query('#selectedModelText'),
    modelOptions: Array.from(document.querySelectorAll('.model-option')),
    sidebarShell: query('.sidebar-shell'),
    sendBtn: query('.send-btn'),
    sendBtnIcon: query('.send-btn-icon'),
    plusBtn: query('.plus-btn'),
    newChatBtn: query('.header-actions .icon-btn[aria-label="New chat"]'),
    exportBtn: query('.header-actions .icon-btn[aria-label="Export"]'),
    sidebarToggleBtn: query('.right-nav .nav-toggle-btn'),
    rightNav: query('.right-nav'),
    avatarBtn: query('#avatarBtn'),
    avatarWrapper: query('.avatar-wrapper'),
    userMenu: query('#userMenu'),
};